name: Documentation issue
description: Highlight a documentation issue
labels:
  - kind/doc
  - needs-triage
body:
  - type: textarea
    id: Inquiry
    attributes:
      label: Inquiry
      description: "Describe what you were looking for in the documentation: "
      placeholder: ex. "How to bootstrap onto AWS."
    validations:
      required: true

  - type: textarea
    id: Improvement
    attributes:
      label: Improvement
      description: "Describe what improvement you would like to see: "
      placeholder: ex. "That there is a document the describes bootstraping AWS and links to recommended configuration for production use."
    validations:
      required: false

  - type: textarea
    id: Info-Notes
    attributes:
      label: "Notes & References"
      description: "Please add relevant notes, other related issues/PRs, anything else to help improve the documentation."
    validations:
      required: false
